version: '2.1'
services:
  test:
    build: .
    depends_on:
      - postgres
      - rabbitmq
    links:
      - postgres
      - rabbitmq
    environment:
      TEST_RABBITMQ_URL: 'amqp://rabbitmq//'
      TEST_DATABASE_URL: 'postgres://postgres:@postgres/test-db'
    command: npm test
    volumes:
      - ./test:/usr/src/app/test
      - ./src:/usr/src/app/src
  postgres:
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    image: postgres:10
  rabbitmq:
    image: rabbitmq
